[pytest]
markers=
    sanity
    regression
    smoke
    api
    performance

# Report configurations
addopts = 
    --html=../reports/report.html 
    --self-contained-html
    --alluredir=../reports/allure-results
    --junit-xml=../reports/junit.xml
    -v

# Test output options
console_output_style = progress
log_cli = true
log_cli_level = INFO
